name: Build Xiaomi QuickApp RPK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build QuickApp RPK
        run: |
          npx aiot build --enable-custom-component

      - name: Check Build Files
        run: |
          ls -R

      - name: Upload RPK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-shelter-rpk
          path: |
            dist/
            build/
            *.rpk
